name: Build MatrixDC Document

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario' 

# Environment variables available to all jobs and steps in this workflow
env:
  DOC_IMAGE_URL: matrixdc/docs
  DEPLOYMENT_NAME: docs

permissions:
  contents: read

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Variable
      id: set-env
      run: |
        echo "DATE=$(TZ=Asia/Shanghai date +'%Y%m%d')" >> $GITHUB_OUTPUT
    - uses: benjlevesque/short-sha@v2.2
      name: Get short commit sha
      id: short-sha
    - name: Show Variable
      run: |
        echo "varibables ${DOC_IMAGE_URL}:${{ steps.set-env.outputs.DATE }}-${{ steps.short-sha.outputs.sha }} "
        
    # Build
    - name: Build Docker image
      run: |
        docker build -t "${DOC_IMAGE_URL}:${{ steps.set-env.outputs.DATE }}-${{ steps.short-sha.outputs.sha }}" .

    - name: Login docker hub
      run: |
        docker login -u ${{ secrets.HUB_USERNAME }} -p '${{ secrets.HUB_SECRET }}'

    # Push the Docker image to docker hub
    - name: Publish image
      run: |
        docker push "${DOC_IMAGE_URL}:${{ steps.set-env.outputs.DATE }}-${{ steps.short-sha.outputs.sha }}"

    - uses: azure/setup-kubectl@v4
    - uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: https://zone1-k8s-apiserver.gw.neolink-ai.com
        k8s-secret: "${{ secrets.K8S_SA_TOKEN }}"
      id: setcontext

    - name: Upgrade the doc service
      run: |
        kubectl set image deployment/docs -n matrixdc-system docs="${DOC_IMAGE_URL}:${{ steps.set-env.outputs.DATE }}-${{ steps.short-sha.outputs.sha }}"
